version: "3.8"

services:
  # PostgreSQL база данных
  postgres:
    image: postgres:15-alpine
    container_name: parcel_delivery_postgres
    environment:
      POSTGRES_DB: parcel_delivery
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - parcel_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis кэш
  redis:
    image: redis:7-alpine
    container_name: parcel_delivery_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - parcel_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: parcel_delivery_backend
    env_file:
      - ./backend/.env
    environment:
      - NODE_ENV=development
      - PORT=8000
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=parcel_delivery
      - DB_USER=postgres
      - DB_PASSWORD=password
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=your-super-secret-jwt-key-change-this-in-production
      - FRONTEND_URL=http://localhost:5173
    ports:
      - "8001:8000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - parcel_network
    restart: unless-stopped

  # Frontend (React приложение)
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: parcel_delivery_frontend
    environment:
      - VITE_API_URL=http://localhost:8001/api
    ports:
      - "5173:3000"
    volumes:
      - ./src:/app/src
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - parcel_network
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local

networks:
  parcel_network:
    driver: bridge
