/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  safelist: [
    "bg-toast-error-bg",
    "text-toast-error-text",
    "border-toast-error-border",
    "bg-toast-success-bg",
    "text-toast-success-text",
    "border-toast-success-border",
    "bg-toast-warning-bg",
    "text-toast-warning-text",
    "border-toast-warning-border",
    "bg-toast-info-bg",
    "text-toast-info-text",
    "border-toast-info-border",
    "bg-status-pending-bg",
    "text-status-pending-text",
    "border-status-pending-border",
    "bg-status-accepted-bg",
    "text-status-accepted-text",
    "border-status-accepted-border",
    "bg-status-completed-bg",
    "text-status-completed-text",
    "border-status-completed-border",
    "bg-status-cancelled-bg",
    "text-status-cancelled-text",
    "border-status-cancelled-border",
    "bg-type-send-bg",
    "text-type-send-text",
    "border-type-send-border",
    "bg-type-receive-bg",
    "text-type-receive-text",
    "border-type-receive-border",
    "bg-credits-zero-bg",
    "text-credits-zero-text",
    "border-credits-zero-border",
    "bg-credits-low-bg",
    "text-credits-low-text",
    "border-credits-low-border",
    "bg-credits-good-bg",
    "text-credits-good-text",
    "border-credits-good-border",
    // Telegram цвета для pull to refresh
    "bg-tg-bg",
    "text-tg-text",
    "bg-tg-secondary-bg",
    "text-tg-button",
    "border-tg-button",
    "border-t-transparent",
    "text-tg-hint",
    "bg-tg-button",
    "text-tg-button-text",
  ],
  theme: {
    extend: {
      colors: {
        // Основные Telegram цвета
        "tg-bg": "#ffffff",
        "tg-text": "#000000",
        "tg-hint": "#666666",
        "tg-button": "#2481cc",
        "tg-button-text": "#ffffff",
        "tg-secondary-bg": "#f8f9fa",

        // Статусы заявок
        "status-pending-bg": "#fef3c7",
        "status-pending-text": "#92400e",
        "status-pending-border": "#f59e0b",
        "status-accepted-bg": "#dbeafe",
        "status-accepted-text": "#1e40af",
        "status-accepted-border": "#3b82f6",
        "status-completed-bg": "#dcfce7",
        "status-completed-text": "#166534",
        "status-completed-border": "#22c55e",
        "status-cancelled-bg": "#fee2e2",
        "status-cancelled-text": "#991b1b",
        "status-cancelled-border": "#ef4444",

        // Типы заявок
        "type-send-bg": "#dbeafe",
        "type-send-text": "#1e40af",
        "type-send-border": "#3b82f6",
        "type-receive-bg": "#e9d5ff",
        "type-receive-text": "#7c3aed",
        "type-receive-border": "#a855f7",

        // Уведомления
        "toast-success-bg": "#10b981",
        "toast-success-text": "#ffffff",
        "toast-success-border": "#059669",
        "toast-error-bg": "#ef4444",
        "toast-error-text": "#ffffff",
        "toast-error-border": "#dc2626",
        "toast-warning-bg": "#f59e0b",
        "toast-warning-text": "#ffffff",
        "toast-warning-border": "#d97706",
        "toast-info-bg": "#3b82f6",
        "toast-info-text": "#ffffff",
        "toast-info-border": "#2563eb",

        // Кредиты
        "credits-zero-bg": "#fee2e2",
        "credits-zero-text": "#991b1b",
        "credits-zero-border": "#ef4444",
        "credits-low-bg": "#fef3c7",
        "credits-low-text": "#92400e",
        "credits-low-border": "#f59e0b",
        "credits-good-bg": "#dcfce7",
        "credits-good-text": "#166534",
        "credits-good-border": "#22c55e",
      },
    },
  },
  plugins: [],
};
